export const FRONTEND_URL = 'http://localhost:5000';
export const DefaultFaculties = [
  {
    faculty: 'FACULTY OF AGRICULTURE AND FORESTRY',
    departments: [
      'DEPARTMENT OF ANIMAL SCIENCE',
      'DEPARTMENT OF AGRICULTURAL ECONOMICS',
      'DEPARTMENT OF AGRONOMY',
      'DEPARTMENT OF FOREST RESOURCES MANAGEMENT',
    ],
  },
  {
    faculty: 'FACULTY OF ARTS',
    departments: [
      'DEPARTMENT OF MUSIC',
      'DEPARTMENT OF RELIGIOUS STUDIES',
      'DEPARTMENT OF ARABIC AND ISLAMIC STUDIES',
      'DEPARTMENT OF COMMUNICATION AND LANGUAGE ARTS',
      'DEPARTMENT OF EUROPEAN STUDIES',
      'DEPARTMENT OF HISTORY',
      'DEPARTMENT OF THEATRE ARTS',
      'DEPARTMENT OF PHILOSOPHY',
    ],
  },
  {
    faculty: 'COLLEGE OF MEDICINE',
    departments: [
      'DEPARTMENT OF HUMAN NUTRITION',
      'DEPARTMENT OF OBSTETRICS AND GYNAECOLOGY',
      'DEPARTMENT OF OPHTHALMOLOGY',
      'DEPARTMENT OF PAEDIATRICS',
      'DEPARTMENT OF PHYSIOTHERAPY',
      'DEPARTMENT OF RADIOTHERAPY',
      'DEPARTMENT OF SURGERY',
      'DEPARTMENT OF BIOCHEMISTRY',
      'DEPARTMENT OF EPIDEMIOLOGY, MEDICAL STATISTICS AND ENVIRONMENTAL HEALTH (EMSEH)',
      'DEPARTMENT OF HEALTH POLICY AND MANAGEMENT',
      'DEPARTMENT OF HEALTH PROMOTION AND EDUCATION',
      'INSTITUTE OF ADVANCED MEDICAL RESEARCH AND TRAINING',
      'DEPARTMENT OF MEDICINE',
      'DEPARTMENT OF PHYSIOLOGY',
      'DEPARTMENT OF PREVENTIVE MEDICINE AND PRIMARY CARE',
      'DEPARTMENT OF PSYCHIATRY',
    ],
  },
  {
    faculty: 'FACULTY OF EDUCATION',
    departments: [
      'DEPARTMENT OF TEACHER EDUCATION',
      'DEPARTMENT OF ADULT EDUCATION',
      'DEPARTMENT OF GUIDANCE AND COUNSELLING',
      'DEPARTMENT OF HUMAN KINETICS AND HEALTH EDUCATION',
    ],
  },
  {
    faculty: 'FACULTY OF PHARMACY',
    departments: ['DEPARTMENT OF PHARMACEUTICS AND INDUSTRIAL PHARMACY'],
  },
  {
    faculty: 'FACULTY OF SCIENCE',
    departments: [
      'DEPARTMENT OF MATHEMATICS',
      'DEPARTMENT OF PHYSICS',
      'DEPARTMENT OF STATISTICS',
      'DEPARTMENT OF BOTANY',
      'DEPARTMENT OF GEOLOGY',
      'DEPARTMENT OF MICROBIOLOGY',
      'DEPARTMENT OF ZOOLOGY',
    ],
  },
  {
    faculty: 'FACULTY OF THE SOCIAL SCIENCES',
    departments: [
      'DEPARTMENT OF PSYCHOLOGY',
      'DEPARTMENT OF ECONOMICS',
      'DEPARTMENT OF GEOGRAPHY',
      'DEPARTMENT OF SOCIOLOGY',
    ],
  },
  {
    faculty: 'FACULTY OF TECHNOLOGY',
    departments: [
      'DEPARTMENT OF ELECTRICAL AND ELECTRONIC ENGINEERING',
      'DEPARTMENT OF MECHANICAL ENGINEERING',
      'DEPARTMENT OF INDUSTRIAL AND PRODUCTION ENGINEERING',
    ],
  },
  {
    faculty: 'FACULTY OF VETERINARY MEDICINE',
    departments: [
      'DEPARTMENT OF VETERINARY PHYSIOLOGY, BIOCHEMISTRY AND PHARMACOLOGY',
    ],
  },
  {
    faculty: 'AFRICA REGIONAL CENTRE FOR INFORMATION SCIENCE',
    departments: [],
  },
];

export const STUDENT_MODEL_NAME = 'Student';
export const COLLECTION_MODEL_NAME = 'Collection';
export const MATERIAL_MODEL_NAME = 'Material';
export const COURSE_MODEL_NAME = 'Course';
export const FACULTY_MODEL_NAME = 'Faculty';
